data_root: dataset_iq
classes:
  - YUNZHUO-H12
  - YUNZHUO-H16
  - YUNZHUO-H30

chunk_size: 32768
nfft: 512
max_chunks_per_file: 100

epochs: 5
batch_size: 16
lr: 0.001
valid_ratio: 0.2
seed: 50

output_dir: fft_100chunks