train: dataset/train
val: dataset/valid

save_path: models/compare_ResNet18
model: resnet18
weights: None

batch_size: 8
image_size: 224
num_classes: 6

class_names:
  YunZhuo-H12: 0
  YunZhuo-H16: 1
  YunZhuo-H30: 2
  DJI MINI4 PRO: 3
  FLYSKY FS I6X: 4
  WFLY WFT09SII : 5
  
device: cpu
num_epochs: 5
shuffle: True
lr: 0.0001
optimizer: AdamW