train: dataset/train
val: dataset/valid
save_path: models/exp1.3_ResNet50
model : resnet50
weights: None
batch_size: 4
image_size: 224
num_classes: 3
class_names:
  YunZhuo-H12: 0
  YunZhuo-H16: 1
  YunZhuo-H30: 2
device: 'cpu'
num_epochs: 3
shuffle: True
lr: 0.00001
optimizer: None
