train: dataset/train
val: dataset/valid
save_path: models/exp1.4_ResNet101
model : resnet101
weights: None
batch_size: 8
image_size: 640
num_classes: 5
class_names: [
        'DJIAVATA2',
        'DJIFPVCOMBO',
        'DJIMAVIC3PRO',
        'DJIMINI3',
        'DJIMINI4PRO',
]
device: 'cpu'
num_epochs: 5
shuffle: True
lr: 0.00001
optimizer: None
